import { Header } from "@/components";
import { SideBar } from "@/components/side-bar/side-bar";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "jotai";
import Providers from "@/atoms/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "flex h-screen w-screen")}>
        <Providers>
          <SideBar />

          <main className="h-full flex-1 flex flex-col">
            <Header />
            <section className="flex-1">{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
